#!/bin/bash

SCRIPT="$0"
SCRIPTDIR="$(dirname $SCRIPT)"
cd "$SCRIPTDIR"

# Kill socat
# kill $(ps aux | grep '[s]ocat' | awk '{print $2}')
# http://stackoverflow.com/questions/3510673/find-and-kill-a-process-in-one-line-using-bash-and-regex

./build_upload && ./term

