#!/bin/bash

SCRIPT="$0"
SCRIPTDIR="$(dirname $SCRIPT)"
cd "$SCRIPTDIR"

ARDUINO_DEV=$(cfget -C ino.ini serial-port)

./configure_port_speed
#socat -d -d -,raw,echo=0 $ARDUINO_DEV,raw,echo=0
socat -d -d -,echo=0 $ARDUINO_DEV,raw,echo=0
